### PR TITLE
Add Wanted Section

### PR DESCRIPTION
**Pull request by spboyer**

### CODE REVIEW

**Comment by natemcmaster** [comment]
Thanks!

**Comment by flagbug** [comment]
@spboyer @natemcmaster 

> Determine out of date Nuget packages

This already exists, it's even in the list of community tools 😄 https://github.com/goenning/dotnet-outdated

**Comment by spboyer** [comment]
@flagbug 

This is a previous *Tool* using the Project based tooling.

```xml
<DotNetCliToolReference Include="DotNetOutdated" Version="x.x.x" />
```

Needs to be updated or branched to be installed globally using the new 2.1 global tools to allow

`dotnet install tool -g  DotNetOutdated`

`dotnet new` template -> `dotnet new --install "McMaster.DotNet.GlobalTool.Templates::2.1.300-preview1"`

cc:/ @goenning

**Comment by natemcmaster** [comment]
Maybe we should split the list into DotNetCli and global tools

**Comment by spboyer** [comment]
@natemcmaster - agreed

**Comment by flagbug** [comment]
@spboyer Aha! Thanks for the clarification!

**Comment by goenning** [comment]
@spboyer @flagbug I'm not actively maintaining DotNetOutdated anymore, so if anyone wants to jump in and take the lead, I can grant access to it on GitHub and NuGet.

**Comment by flagbug** [comment]
@goenning Sure, I'd love to continue maintaining the project, it's the number one thing I'm missing for .NET Core!

**Pull request merged**
